In [2]:
import pandas as pd

In [3]:

df = pd.read_csv('adidas_dataset_1200rows.csv')
df.head()

,Order_ID,Order_Date,SKU,Product_Name,Category,Region,Store_Type,Units_Sold,Unit_Price,Discount,Revenue,Profit,Customer_Age,Gender,Payment_Method
0,101178,2024-09-21,AD-1877-D,Tiro 23 Track Pants,Apparel,Asia-Pacific,Online,5,49.68,0,248.40,70.40,35,Female,NetBanking
1,100865,2024-09-04,AD-1745-B,Essentials Tee,Apparel,Europe,Online,2,27.07,0,54.14,11.35,48,Female,NetBanking
2,100101,2024-09-24,AD-8110-A,Superstar,Footwear,Asia-Pacific,Online,3,96.58,20,231.79,61.86,34,Male,Debit Card
3,100439,2024-01-03,AD-4892-C,Performance Socks (3-pack),Accessories,Latin America,Retail,5,17.49,10,78.70,35.99,30,Female,Apple Pay
4,100058,2023-10-07,AD-8657-B,Originals Backpack,Accessories,Europe,Retail,3,58.96,5,168.04,68.38,30,Female,PayPal

In [6]:
total_revenue = df['Revenue'].sum()

In [7]:
total_profit = df['Profit'].sum()

In [8]:
total_units = df['Units_Sold'].sum()

In [9]:
avg_order_value = df['Revenue'].mean()

In [11]:
print("Performance of sales channel by store type")
store_summary = df.groupby('Store_Type')[['Revenue', 'Profit', 'Units_Sold']].sum().sort_values(by='Revenue', ascending=False)
print(store_summary)

Performance of sales channel by store type
              Revenue    Profit  Units_Sold
Store_Type
Online      133207.12  39224.35        1601
Retail      102147.08  30288.41        1263
Outlet       33516.27  10081.42         427
Wholesale    18507.45   5475.67         259

In [12]:
print("Performance by Region ")
region_summary = df.groupby('Region')[['Revenue', 'Profit', 'Units_Sold']].sum().sort_values(by='Revenue', ascending=False)
print(region_summary)
print("\n")

Performance by Region
                       Revenue    Profit  Units_Sold
Region
Asia-Pacific          86027.88  25519.31        1044
North America         81724.56  24051.61        1077
Europe                69057.16  20403.56         835
Latin America         32966.34   9846.85         361
Middle East & Africa  17601.98   5248.52         233

In [13]:
print(" Top 5 Best-Selling Products ")
top_products = df.groupby('Product_Name')[['Revenue', 'Profit', 'Units_Sold']].sum().sort_values(by='Revenue', ascending=False).head(5)
print(top_products)
print("\n")

 Top 5 Best-Selling Products
                    Revenue   Profit  Units_Sold
Product_Name
Predator Freak     31599.08  9218.42         153
Ultraboost Light   30192.09  8876.32         212
Primegreen Jacket  27720.09  7687.40         217
Copa Sense         27178.45  8086.74         180
Ultraboost 22      25555.62  7680.82         152

In [14]:
print(" Performance by Category ")
category_summary = df.groupby('Category')[['Revenue', 'Profit', 'Units_Sold']].sum().sort_values(by='Revenue', ascending=False)
print(category_summary)
print("\n")

 Performance by Category
               Revenue    Profit  Units_Sold
Category
Footwear     179005.62  52827.63        1500
Apparel       77377.83  22056.46        1022
Accessories   30994.47  10185.76        1028

### Gross Revenue

In [16]:
df['Gross_Revenue'] = df['Units_Sold'] * df['Unit_Price']

### Total Discount Amount

In [17]:
df['Discount_Amount'] = (df['Gross_Revenue'] * (df['Discount'] / 100)).round(2)

### Profit Margin

In [18]:
df['Profit_Margin_%'] = ((df['Profit'] / df['Revenue']) * 100).round(2)

In [19]:
df.head()

,Order_ID,Order_Date,SKU,Product_Name,Category,Region,Store_Type,Units_Sold,Unit_Price,Discount,Revenue,Profit,Customer_Age,Gender,Payment_Method,Gross_Revenue,Discount_Amount,Profit_Margin_%
0,101178,2024-09-21,AD-1877-D,Tiro 23 Track Pants,Apparel,Asia-Pacific,Online,5,49.68,0,248.40,70.40,35,Female,NetBanking,248.40,0.00,28.34
1,100865,2024-09-04,AD-1745-B,Essentials Tee,Apparel,Europe,Online,2,27.07,0,54.14,11.35,48,Female,NetBanking,54.14,0.00,20.96
2,100101,2024-09-24,AD-8110-A,Superstar,Footwear,Asia-Pacific,Online,3,96.58,20,231.79,61.86,34,Male,Debit Card,289.74,57.95,26.69
3,100439,2024-01-03,AD-4892-C,Performance Socks (3-pack),Accessories,Latin America,Retail,5,17.49,10,78.70,35.99,30,Female,Apple Pay,87.45,8.74,45.73
4,100058,2023-10-07,AD-8657-B,Originals Backpack,Accessories,Europe,Retail,3,58.96,5,168.04,68.38,30,Female,PayPal,176.88,8.84,40.69